server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=test-route
spring.cloud.gateway.server.webmvc.routes[0].uri=https://httpbin.org
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/test/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[1].id=demo-route
spring.cloud.gateway.server.webmvc.routes[1].uri=https://httpbin.org
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/demo/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/demo/(?<segment>.*), /${segment}